### ISSUE TITLE
Curse username/password

### ISSUE THREAD

**Issue by leothelocust** [amcoder/curse_client#12]
I linked my account through twitch, but when I use those credentials, it does not work.

For example:

I type this in cli:
```
curse show "FTB Beyond"
```
the output is below:
```
Loading project information from curse
Curse username: leothelocust
Curse password: [enter twitch password]
Inavlid username or password
Cannot find modpack FTB Beyond
```
_and yes, your code does misspell "Invalid" as well._

As you can see, my credentials don't work.  Do I need to create a specific account on curse?

Thank you in advance!
-Levi

**Comment by meson11** [comment]
same here

**Comment by meepcode** [comment]
Login with your original curse credentials. I had the same problem until I did that and it worked.

**Comment by meson11** [comment]
if i have no original curse credentials?

**Comment by meepcode** [comment]
Create 'em I guess

**Comment by darkpoetcc** [comment]
And how would you suggest creating them, exactly?  There is no obvious way to do that, as the website forces you to login with your Twitch account.

**Comment by Toorero** [comment]
Same problem here but in the install section

I will get the same error regarding on the command [show/install]:

<pre>Curse Password: <b>Traceback</b> (most recent call last):
	12: from /usr/local/bin/curse:23:in `&lt;main&gt;&apos;
	11: from /usr/local/bin/curse:23:in `load&apos;
	10: from /var/lib/gems/2.5.0/gems/curse_client-0.1.4/exe/curse:5:in `&lt;top (required)&gt;&apos;
	 9: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start&apos;
	 8: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch&apos;
	 7: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command&apos;
	 6: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run&apos;
	 5: from /var/lib/gems/2.5.0/gems/curse_client-0.1.4/lib/curse_client/cli.rb:23:in `show&apos;
	 4: from /var/lib/gems/2.5.0/gems/curse_client-0.1.4/lib/curse_client/client.rb:34:in `find_by_name&apos;
	 3: from /var/lib/gems/2.5.0/gems/curse_client-0.1.4/lib/curse_client/client.rb:38:in `addon&apos;
	 2: from /var/lib/gems/2.5.0/gems/curse_client-0.1.4/lib/curse_client/client.rb:66:in `with_authentication&apos;
	 1: from /var/lib/gems/2.5.0/gems/curse_client-0.1.4/lib/curse_client/client.rb:69:in `rescue in with_authentication&apos;
/var/lib/gems/2.5.0/gems/curse_client-0.1.4/lib/curse_client/client.rb:76:in `authenticate&apos;: <b>undefined method `noecho&apos; for #&lt;IO:&lt;STDIN&gt;&gt; (</b><u style="text-decoration-style:single"><b>NoMethodError</b></u><b>)</b></pre>
