### ISSUE TITLE
'get_json' request fails when modname contains a single-quote

### ISSUE THREAD

**Issue by birdspider** [amcoder/curse_client#6]
While installing "FTB Infinity Evolved" works, the same with "IanAnderson's Modpack" does not.
I suspect the \' (single-quote) to be incorrectly encoded/sanitized and forcing the server into a 500.

Any more info I can provide ?

----

Works:
```
curse install "FTB Infinity Evolved"
Loading project information from curse
Installing FTB Infinity Evolved
Downloading https://addons.cursecdn.com/files/2320/896/FTBInfinity-2.6.0-1.7.10.zip
...
```

Does not work:
```
~/test $ curse show "IanAnderson's Modpack"                         
Loading project information from curse
IanAnderson's Modpack
Summary: A mix of the latest mods
Authors: iananderson
Url: https://mods.curse.com/modpacks/minecraft/244691-ianandersons-modpack
Categories: Exploration, Extra Large, Magic, Multiplayer, Tech
Downloads: 1918.0
Popularity: 29.585500717163086
Files:
/usr/lib/ruby/2.3.0/net/http/response.rb:120:in `error!': 500 "Internal Server Error" (Net::HTTPFatalError)
        from /home/<user>/.gem/ruby/2.3.0/gems/curse_client-0.1.2/lib/curse_client/api.rb:59:in `get_json'
        from /home/<user>/.gem/ruby/2.3.0/gems/curse_client-0.1.2/lib/curse_client/api.rb:39:in `addon_files'
        from /home/<user>/.gem/ruby/2.3.0/gems/curse_client-0.1.2/lib/curse_client/client.rb:45:in `block in addon_files'
        from /home/<user>/.gem/ruby/2.3.0/gems/curse_client-0.1.2/lib/curse_client/client.rb:67:in `with_authentication'
        from /home/<user>/.gem/ruby/2.3.0/gems/curse_client-0.1.2/lib/curse_client/client.rb:44:in `addon_files'
        from /home/<user>/.gem/ruby/2.3.0/gems/curse_client-0.1.2/lib/curse_client/cli.rb:34:in `show'
        from /home/<user>/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/<user>/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/<user>/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/<user>/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/<user>/.gem/ruby/2.3.0/gems/curse_client-0.1.2/exe/curse:5:in `<top (required)>'
        from /home/<user>/.gem/ruby/2.3.0/bin/curse:23:in `load'
        from /home/<user>/.gem/ruby/2.3.0/bin/curse:23:in `<main>'

~/test $ curse install "IanAnderson's Modpack"
Loading project information from curse
/usr/lib/ruby/2.3.0/net/http/response.rb:120:in `error!': 500 "Internal Server Error" (Net::HTTPFatalError)
        from /home/<user>/.gem/ruby/2.3.0/gems/curse_client-0.1.2/lib/curse_client/api.rb:59:in `get_json'
        from /home/<user>/.gem/ruby/2.3.0/gems/curse_client-0.1.2/lib/curse_client/api.rb:39:in `addon_files'
        from /home/<user>/.gem/ruby/2.3.0/gems/curse_client-0.1.2/lib/curse_client/client.rb:45:in `block in addon_files'
        from /home/<user>/.gem/ruby/2.3.0/gems/curse_client-0.1.2/lib/curse_client/client.rb:67:in `with_authentication'
        from /home/<user>/.gem/ruby/2.3.0/gems/curse_client-0.1.2/lib/curse_client/client.rb:44:in `addon_files'
        from /home/<user>/.gem/ruby/2.3.0/gems/curse_client-0.1.2/lib/curse_client/installer.rb:37:in `find_file'
        from /home/<user>/.gem/ruby/2.3.0/gems/curse_client-0.1.2/lib/curse_client/installer.rb:8:in `install'
        from /home/<user>/.gem/ruby/2.3.0/gems/curse_client-0.1.2/lib/curse_client/client.rb:58:in `install'
        from /home/<user>/.gem/ruby/2.3.0/gems/curse_client-0.1.2/lib/curse_client/cli.rb:48:in `install'
        from /home/<user>/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/<user>/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/<user>/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/<user>/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/<user>/.gem/ruby/2.3.0/gems/curse_client-0.1.2/exe/curse:5:in `<top (required)>'
        from /home/<user>/.gem/ruby/2.3.0/bin/curse:23:in `load'
        from /home/<user>/.gem/ruby/2.3.0/bin/curse:23:in `<main>
```

**Comment by amcoder** [comment]
@birdspider This should be fixed now. It was a server issue, so you shouldn't have to update the client. Let me know if you still run into problems.
